package GUI;

import ENTITY.NhanVien;
import UTILS.Auth;
import UTILS.MsgBox;
import java.awt.Color;
import java.awt.Font;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.Properties;
import javax.mail.Message;
import javax.mail.PasswordAuthentication;
import javax.mail.Session;
import javax.mail.Transport;
import javax.mail.internet.InternetAddress;
import javax.mail.internet.MimeMessage;

/**
 *
 * @author admin
 */
public class QuenMatKhau extends javax.swing.JFrame implements Runnable{

    /**
     * Creates new form QuenMatKhau
     */
    public QuenMatKhau() {
        initComponents();
    }
    public QuenMatKhau(int code, int minutes){
        initComponents();
        setLocationRelativeTo(null);
        OTP = code;
        minute = minutes;
        Thread t = new Thread(this);
        t.start();
    }
    int OTP, minute;
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblThongBao = new javax.swing.JLabel();
        txtConfirm = new javax.swing.JTextField();
        lblReSend = new javax.swing.JLabel();
        btnCancel = new javax.swing.JButton();
        btnOK = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        lblThongBao.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblThongBao.setText("Bạn đã được nhận mã xác thực có 6 chữ số, vui lòng nhập mã xác thực");

        lblReSend.setText("Gửi lại mã");
        lblReSend.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                lblReSendMouseMoved(evt);
            }
        });
        lblReSend.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblReSendMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblReSendMouseExited(evt);
            }
        });

        btnCancel.setText("Cancel");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });

        btnOK.setText("OK");
        btnOK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOKActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblThongBao, javax.swing.GroupLayout.DEFAULT_SIZE, 397, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(btnOK, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(btnCancel))
                                .addComponent(txtConfirm, javax.swing.GroupLayout.PREFERRED_SIZE, 386, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(lblReSend))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(lblThongBao)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtConfirm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblReSend)
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCancel)
                    .addComponent(btnOK))
                .addContainerGap(33, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    void confirmCode(){
        if (txtConfirm.getText().length()<6){
            lblThongBao.setText("");
            lblThongBao.setText("Mã xác thực không đúng, vui lòng nhập lại");
        } 
        else{
            String confirm = txtConfirm.getText();
            if (confirm != null) {
                if (!confirm.equals(String.valueOf(OTP))) {
                    lblThongBao.setText("");
                    lblThongBao.setText("Mã xác thực không đúng, vui lòng nhập lại");
                }
                else{
                    new ChangePassword("true").setVisible(true);
                    this.dispose();
                }
            }
        }
    }
    void reSendCode(){
        OTP = (int) Math.floor(((Math.random() * 899999) + 100000));
        String username = "truongson9a2nd@gmail.com";
        String password = "ztywchbxjblibdir";

        Properties prop = new Properties();
        prop.put("mail.smtp.host", "smtp.gmail.com");
        prop.put("mail.smtp.port", "587");
        prop.put("mail.smtp.auth", "true");
        prop.put("mail.smtp.starttls.enable", "true");

        Session session = Session.getInstance(prop,
                new javax.mail.Authenticator() {
            @Override
            protected PasswordAuthentication getPasswordAuthentication() {
                return new PasswordAuthentication(username, password);
            }
        });

        try {

            MimeMessage message = new MimeMessage(session);
            message.setFrom(new InternetAddress(username));
            message.setRecipients(
                    Message.RecipientType.TO,
                    InternetAddress.parse(Auth.user.getEmail())
            );
            message.setSubject("");
            message.setContent("<html><b>"+OTP+"</b></html>" + " là mã xác nhận mật khẩu của bạn", "text/html; charset=utf-8");

            Transport.send(message);
            
            lblThongBao.setText("");
            lblThongBao.setText("Mã xác thực đã được gửi lại, vui lòng nhập mã xác thực");
            minute = new Date().getMinutes();
            Thread t = new Thread(this);
            t.start();
        }
        catch (Exception e){
            e.printStackTrace();
        }
    }
    private void lblReSendMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblReSendMouseClicked
        reSendCode();
    }//GEN-LAST:event_lblReSendMouseClicked

    private void lblReSendMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblReSendMouseMoved
        lblReSend.setFont(new Font("Segoe UI", 1, 12));
        lblReSend.setText("<html><u>Gửi lại mã</u></html>");
        lblReSend.setForeground(Color.blue);
    }//GEN-LAST:event_lblReSendMouseMoved

    private void lblReSendMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblReSendMouseExited
        lblReSend.setFont(new Font("Segoe UI", 0, 12));
        lblReSend.setText("Gửi lại mã");
        lblReSend.setForeground(Color.black);
    }//GEN-LAST:event_lblReSendMouseExited

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnCancelActionPerformed

    private void btnOKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOKActionPerformed
        confirmCode();
    }//GEN-LAST:event_btnOKActionPerformed
    @Override
    public void run(){
        int futMinute = 0;
        while (futMinute - minute < 1){
            try{
                Date now = new Date();
                futMinute = now.getMinutes();
                Thread.sleep(6000);
            }
            catch(Exception ex){
                break;
            }
        }
        lblThongBao.setText("");
        lblThongBao.setText("Mã xác thực đã hết hiệu lực, nhấn vào Gửi lại mã để lấy mã mới");
        OTP = -1;
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(QuenMatKhau.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(QuenMatKhau.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(QuenMatKhau.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(QuenMatKhau.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new QuenMatKhau().setVisible(false);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnOK;
    private javax.swing.JLabel lblReSend;
    private javax.swing.JLabel lblThongBao;
    private javax.swing.JTextField txtConfirm;
    // End of variables declaration//GEN-END:variables
}
